### ISSUE TITLE
Add support for open-source LLMs

### ISSUE THREAD

**Issue by dmitryshurov** [AI-in-Hand/platform#85]
Adding LLaMA support would be really great :)

**Comment by bonk1t** [comment]
Hi @dmitryshurov,

Thank you for your suggestion! We would love to support open-source models like LLaMA. However, we currently rely on the Agency Swarm library, which only supports the OpenAI Assistants API at the moment.

According to their plans, Agency Swarm intends to integrate with https://github.com/datastax/astra-assistants-api in the future (related issues: [#112](https://github.com/VRSEN/agency-swarm/issues/112), [#92](https://github.com/VRSEN/agency-swarm/issues/92)). As soon as this integration is available, we will be able to add support for open-source models in our project.

We appreciate your interest and will keep you updated on any progress!

Best regards,
Nick
